# Demo: Multivariable Regression on Boston Housing Data

In [6]:
import pandas as pd
import numpy as np

names =['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE',  'DIS', 'RAD', 'TAX', 'PTRATIO', 'B', 'LSTAT', 'PRICE']

df = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/housing/housing.data', 
                 header=None, delim_whitespace=True, names=names, na_values='?')

"""
Attribute Information:
    1.  CRIM      per capita crime rate by town
    2.  ZN        proportion of residential land zoned for lots over 
                  25,000 sq.ft.
    3.  INDUS     proportion of non-retail business acres per town
    4.  CHAS      Charles River dummy variable (= 1 if tract bounds 
                  river; 0 otherwise)
    5.  NOX       nitric oxides concentration (parts per 10 million)
    6.  RM        average number of rooms per dwelling
    7.  AGE       proportion of owner-occupied units built prior to 1940
    8.  DIS       weighted distances to five Boston employment centres
    9.  RAD       index of accessibility to radial highways
    10. TAX       full-value property-tax rate per $10,000
    11. PTRATIO   pupil-teacher ratio by town
    12. B         1000(Bk - 0.63)^2 where Bk is the proportion of blocks by town
    13. LSTAT     % lower status of the population
    14. MEDV      Median value of owner-occupied homes in $1000's
"""

"\nAttribute Information:\n    1.  CRIM      per capita crime rate by town\n    2.  ZN        proportion of residential land zoned for lots over \n                  25,000 sq.ft.\n    3.  INDUS     proportion of non-retail business acres per town\n    4.  CHAS      Charles River dummy variable (= 1 if tract bounds \n                  river; 0 otherwise)\n    5.  NOX       nitric oxides concentration (parts per 10 million)\n    6.  RM        average number of rooms per dwelling\n    7.  AGE       proportion of owner-occupied units built prior to 1940\n    8.  DIS       weighted distances to five Boston employment centres\n    9.  RAD       index of accessibility to radial highways\n    10. TAX       full-value property-tax rate per $10,000\n    11. PTRATIO   pupil-teacher ratio by town\n    12. B         1000(Bk - 0.63)^2 where Bk is the proportion of blocks by town\n    13. LSTAT     % lower status of the population\n    14. MEDV      Median value of owner-occupied homes in $1000's\n"

## Forming the Design Matrix

We want to put our features into feature vectors (stacked into a design matrix). Here we check the difference between the numpy and pandas datatype, and see the importance of using ```df['feature'].values``` to get a numpy array returned.

In [7]:
print(df.columns.to_list())

['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX', 'PTRATIO', 'B', 'LSTAT', 'PRICE']


In [8]:
features=df.columns.to_list()
features.remove('PRICE')
print(features)

['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX', 'PTRATIO', 'B', 'LSTAT']


Treat all the features as a vector, $\mathbf{x}$, and stack the samples in a $N$ by $D$ matrix, $X$, where $N$ is the number of samples and $D$ is the number of features.

In [9]:
print(df)

        CRIM    ZN  INDUS  CHAS    NOX  ...    TAX  PTRATIO       B  LSTAT  PRICE
0    0.00632  18.0   2.31     0  0.538  ...  296.0     15.3  396.90   4.98   24.0
1    0.02731   0.0   7.07     0  0.469  ...  242.0     17.8  396.90   9.14   21.6
2    0.02729   0.0   7.07     0  0.469  ...  242.0     17.8  392.83   4.03   34.7
3    0.03237   0.0   2.18     0  0.458  ...  222.0     18.7  394.63   2.94   33.4
4    0.06905   0.0   2.18     0  0.458  ...  222.0     18.7  396.90   5.33   36.2
..       ...   ...    ...   ...    ...  ...    ...      ...     ...    ...    ...
501  0.06263   0.0  11.93     0  0.573  ...  273.0     21.0  391.99   9.67   22.4
502  0.04527   0.0  11.93     0  0.573  ...  273.0     21.0  396.90   9.08   20.6
503  0.06076   0.0  11.93     0  0.573  ...  273.0     21.0  396.90   5.64   23.9
504  0.10959   0.0  11.93     0  0.573  ...  273.0     21.0  393.45   6.48   22.0
505  0.04741   0.0  11.93     0  0.573  ...  273.0     21.0  396.90   7.88   11.9

[506 rows x 14 

In [10]:
# Features
X = df[features].values
print(X)
print(X.shape)
print(f"The dataset contains {X.shape[0]} data points with {X.shape[1]} features")

[[6.3200e-03 1.8000e+01 2.3100e+00 ... 1.5300e+01 3.9690e+02 4.9800e+00]
 [2.7310e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9690e+02 9.1400e+00]
 [2.7290e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9283e+02 4.0300e+00]
 ...
 [6.0760e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 5.6400e+00]
 [1.0959e-01 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9345e+02 6.4800e+00]
 [4.7410e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 7.8800e+00]]
(506, 13)
The dataset contains 506 data points with 13 features


In [11]:
# Labels
y = df['PRICE'].values
print(y.shape)
y = y.reshape(-1,1)
print(y.shape)

(506,)
(506, 1)


# Linear Regression

We are going to use [sklearn](https://scikit-learn.org/stable/modules/linear_model.html#ordinary-least-squares).

First, we define a linear regression model and we fit the model to our data.

In [22]:
from sklearn.linear_model import LinearRegression

regr = LinearRegression(fit_intercept=True)
regr.fit(X,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

The accuracy of the model could be evaluated by finding the MSE between the model prediction and corresponding data points

In [13]:
y_hat = regr.predict(X)  # Model prediction
print(y_hat.shape)

(506, 1)


In [23]:
MSE = np.mean((y-y_hat)**2)
print(MSE)

21.894831181729206


### Here are the parameter of the model :

In [15]:
print(regr.coef_)        # this is [w_1, ...., w_n]
print(regr.intercept_)   # this the bias w_0

[[-1.08011358e-01  4.64204584e-02  2.05586264e-02  2.68673382e+00
  -1.77666112e+01  3.80986521e+00  6.92224640e-04 -1.47556685e+00
   3.06049479e-01 -1.23345939e-02 -9.52747232e-01  9.31168327e-03
  -5.24758378e-01]]
[36.45948839]


### Here is a fancy way to compare $y$ and $\hat{y}$ :

In [16]:
Y = np.hstack([y, y_hat])
with np.printoptions(precision=2):
    print(Y[:10,:])

[[24.   30.  ]
 [21.6  25.03]
 [34.7  30.57]
 [33.4  28.61]
 [36.2  27.94]
 [28.7  25.26]
 [22.9  23.  ]
 [27.1  19.54]
 [16.5  11.52]
 [18.9  18.92]]


# Exercise : 
Compute the Least square solution with numpy and compare your result with the one of sklearn !

In [36]:
X = df[features].values
print (X.shape)

(506, 13)


In [40]:
X = df[features].values
bias_term = np.ones((X.shape[0], 1))
X = np.hstack([bias_term, X])
# pseudo-inverse
w = np.linalg.inv(X.transpose().dot(X)).dot(X.transpose().dot(y))
print ("weights: \n", w[1:14])
print ("intercept:\n", w[0])

weights: 
 [[-1.08011358e-01]
 [ 4.64204584e-02]
 [ 2.05586264e-02]
 [ 2.68673382e+00]
 [-1.77666112e+01]
 [ 3.80986521e+00]
 [ 6.92224640e-04]
 [-1.47556685e+00]
 [ 3.06049479e-01]
 [-1.23345939e-02]
 [-9.52747232e-01]
 [ 9.31168327e-03]
 [-5.24758378e-01]]
intercept:
 [36.45948839]


In [41]:
y_hat = X.dot(w)
Y = np.hstack([y, y_hat])
with np.printoptions(precision=2):
    print(Y[:10,:])

[[24.   30.  ]
 [21.6  25.03]
 [34.7  30.57]
 [33.4  28.61]
 [36.2  27.94]
 [28.7  25.26]
 [22.9  23.  ]
 [27.1  19.54]
 [16.5  11.52]
 [18.9  18.92]]
